### ISSUE TITLE
I wish the tool could dump all NTFS metadata

### ISSUE THREAD

**Issue by Ark-kun** [thewhiteninja/ntfstool#14]
Here was the situation when I discovered this tool:

My HDD stopped being recognized by Windows (shown as Raw). But the problem seems to be very minor. All files are still there. The HDD tools can easily show them. I want to run `chkdsk` to fix the filesystem, but there is a risk that it will mess up everything. I'm pretty sure it won't mess up the file contents. But it could mess up `$MFT`. So, I wanted to back up the whole filesystem table (`$MFT` and `FILE` records). This way I could recover the table or the files (knowing their sectors). It would be also great to compare the table before and after the repair.

I've since fixed my problem, but just wanted to leave my use case here.

**Comment by thewhiteninja** [comment]
You can backup the $MFT table (with the records) ([extract](https://github.com/thewhiteninja/ntfstool/blob/master/README.md#extract)) but restoring only the $MFT will probably (I would say at 99%) break the filesystem as the $MFT is closely linked to the file data.
If chkdsk modify the $MFT and some data (ex: move a file), if you restore the old $MFT, you will lost some data.

The only and the best solution is to backup the whole disk/partition and, if chkdsk messed up the filesystem, restore it.

The ntfstool is not made for backup/restore. But you can backup a drive or volume using the [image](https://github.com/thewhiteninja/ntfstool#image) command and restore using tools that support raw/dd image like [Rufus](https://rufus.akeo.ie/)

Comparing two $MFTs is not easy as the differences can be anywhere, but it's might be possible using a Hex Editor and some time :)
