### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vbs29** [thewhiteninja/ntfstool#16]
I got the following error while trying to build the tool (Debug mode, x64):
'std::shared_ptr<Buffer<PEFS_FEK>> decrypt_fek(RSA *,std::shared_ptr<Buffer<PBYTE>>)': cannot convert argument 1 from 'const rsa_st *' to 'RSA *'	
from ntfstool\Sources\Commands\command_efs.decrypt.cpp, line 172.
**Environment:** Windows 10, Visual Studio 2022 Community.

**Comment by thewhiteninja** [comment]
Fixed in 26332f16b505c8c67fb93cb37a71a32d5d1234bf

Need more time to remove the others warnings since OpenSSL 3.0 but it's on the todo list.
