### ISSUE TITLE
Aes-cbc-128-diffuser  fvek cannot be decrypted correctly

### ISSUE THREAD

**Issue by d2262272d** [thewhiteninja/ntfstool#17]
FVE Version    : 2
State          : ENCRYPTED
Size           : 10485760000 (9.77 GiBs)
Encrypted Size : 10485759488 (9.77 GiBs)
Algorithm      : AES-CBC-128-DIFFUSER
Decrypted img file data error ,Hexadecimal img file，header not is EB 52 90 4E 54 46 53 20

**Comment by d2262272d** [comment]
Is there a command parameter I don't know

**Comment by d2262272d** [comment]
Holy Shit！！！Download the latest binaries on [AppVeyor] is right...

**Comment by thewhiteninja** [comment]
How did you try to decrypt the image file?
Is the FVEK correct?

Decryption is working as expected on my test image.

**Comment by d2262272d** [comment]
FVEK correct！
Release decryption error in code compilation.
but,Download... is correct !
be careful，Self compiled source code NODIFFUSER is correct ...

**Comment by d2262272d** [comment]
Is it because I compiled it with vs19？

**Comment by d2262272d** [comment]
![image](https://user-images.githubusercontent.com/31273818/163513054-905477bc-a0cb-4326-8795-e0771512ff62.png)
Execution
![image](https://user-images.githubusercontent.com/31273818/163513123-6fa78548-05ab-4ccf-8824-3a5d55a90d8a.png)

**Comment by d2262272d** [comment]
It has nothing to do with vs version

**Comment by thewhiteninja** [comment]
Problem fixed after a9a718074a0eb2732ffe8cfe0f1823075555cefb

I don't know why it was not working, maybe a change in openssl or I changed something :)
Binaries will be available soon on AppVeyor.

**Comment by d2262272d** [comment]
nice~！！！！
