### ISSUE TITLE
There is a memory leak in command_bitdecrypt.cpp

### ISSUE THREAD

**Issue by lsw29475** [thewhiteninja/ntfstool#2]
In line 85 of command_bitdecrypt.cpp, you call EVP_CIPHER_CTX_new to initialize, but you call EVP_CIPHER_CTX_free to release when the decryption is complete. This will cause the decrypt_sector_fn that is continuously called during decryption to cause memory leaks

**Comment by thewhiteninja** [comment]
Calling EVP_CIPHER_CTX_cleanup in the decrypt_sector_fn seems to be enough to avoid the leak, right?

**Comment by lsw29475** [comment]
Yes，You just need to release after calling&nbsp;decrypt_sector_fn&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 凌晨4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thewhiteninja/ntfstool] There is a memory leak in command_bitdecrypt.cpp (#2)





 
Calling EVP_CIPHER_CTX_cleanup in the decrypt_sector_fn seems to be enough to avoid the leak, right?

**Comment by thewhiteninja** [comment]
Fixed in 35de6eab02e3324a60cdea3cb733c91c3a8bf410
