### ISSUE TITLE
Long output filename (possibly) causing hang

### ISSUE THREAD

**Issue by Bloggzy** [thewhiteninja/ntfstool#21]
Firstly, great tool, really excellent, thank you!

This relates to the mft.dump function.

I've found (in some instances) that the process seems to hang, i.e. never completes. I'm not completely sure of the cause, but did note that when I specified a long filename as the output file, the hang occurred. I'm not completely set on this being the cause, as with other testing, I've been able to specify long output filenames with no issue. Please see screenshot below for an example:

![NtfsTool-Long-Output-Filename-Hang](https://user-images.githubusercontent.com/46377651/179875070-d5d0ffeb-ce22-4c8e-b2d3-54d77a034d82.png)

**Comment by thewhiteninja** [comment]
I can't reproduce the bug, I tried with short, long and very long filenames.
It's a simple CreateFile, maybe the call succeeded and it hangs during the dump.

Do you know if the file "hostname_driveletter_mft.raw" was created?

**Comment by Bloggzy** [comment]
No worries, thanks for looking, I appreciate your time. I wasn't completely sure if it was connected to the long file name, so if I can reproduce the issue with anymore frequency I will let you know.

**Comment by Bloggzy** [comment]
Issue closed - unable to reproduce consistently - unknown cause.
