### ISSUE TITLE
Working with .\ntfstool.x64.exe undelete

### ISSUE THREAD

**Issue by leoplac** [thewhiteninja/ntfstool#22]
Hi guys

is there a way to filter the results from undelete command or export the results to a .csv or .txt file without those break lines in the filename so I be able to analyze in mysql for example?

This is the results I got:
![image](https://user-images.githubusercontent.com/79605015/191142362-4d39e94a-3ca0-4f7c-b262-77e42c029325.png)

The results I need:
![image](https://user-images.githubusercontent.com/79605015/191142622-477816ae-3c60-4652-b35b-b45237acd079.png)

Thank you!

**Comment by thewhiteninja** [comment]
I will add an option to write results in a CSV file :+1:

**Comment by thewhiteninja** [comment]
Added in 53a6000f65d0a6c5ff5412fa9af12a65bdc297ae
Binaries will be available soon on https://ci.appveyor.com/project/thewhiteninja/ntfstool

**Comment by leoplac** [comment]
> Added in [53a6000](https://github.com/thewhiteninja/ntfstool/commit/53a6000f65d0a6c5ff5412fa9af12a65bdc297ae) Binaries will be available soon on https://ci.appveyor.com/project/thewhiteninja/ntfstool Example here: https://github.com/thewhiteninja/ntfstool#undelete

Thank you @thewhiteninja!!

One more question: I am total amateur regarding codes etc. so in the first time I downloaded the .exe and just ran the command as in the readme.txt but now I noticed that you have updated the binares, so, do I need to download the code and compile in a Dev++ for example? Thanks!

**Comment by thewhiteninja** [comment]
You can compile it with [Visual Studio 2022 Community Edition](https://visualstudio.microsoft.com/fr/vs/community/) (which is free). Steps [here](https://github.com/thewhiteninja/ntfstool#build)
But if you only need to run it, like most people, downloading the last version of the binary from [AppVeyor](https://ci.appveyor.com/project/thewhiteninja/ntfstool) is the best way to use it.
