### ISSUE TITLE
program keeps crashing on record_from_path or attribute_header

### ISSUE THREAD

**Issue by bleriaf** [thewhiteninja/ntfstool#26]
hello i'm trying to use this as a library for some stuff i need however i keep noticing (maybe a race condition) a crash on record_from_number, since sometimes it happens and sometimes it doesn't but maybe i'm just doing something wrong and if so maybe you could tell me? all you have to do is run this code in a loop and after a while it will end up crashing in record_from_number

this code worked for 2 iterations then crashed, sometimes it instantly crashes sometimes after a while it's really random
```
while ( true ) {
		for ( const auto& disk : core::win::disks::list( ) ) {
			if ( !disk )
				continue;

			for ( const auto& volume : disk->volumes( ) ) {
				if ( !volume )
					continue;

				const auto explorer = std::make_shared<NTFSExplorer>( volume );
				if ( !explorer || !explorer->mft( ) )
					continue;

				const std::shared_ptr<MFTRecord> entry_rec = explorer->mft( )->record_from_path( ( R"(\$Extend\$ObjId)" ) );
				if ( !entry_rec )
					continue;

				PMFT_RECORD_ATTRIBUTE_HEADER stdinfo_att = entry_rec->attribute_header( $STANDARD_INFORMATION );
				if ( !stdinfo_att )
					continue;

				const auto stdinfo = POINTER_ADD( PMFT_RECORD_ATTRIBUTE_STANDARD_INFORMATION, stdinfo_att, stdinfo_att->Form.Resident.ValueOffset );
				if ( !stdinfo )
					continue;

				printf( "%s | %p \n", volume->name( ).c_str( ), stdinfo );
			}
		}	
	}
```

![1pzTQex](https://user-images.githubusercontent.com/109803937/224331547-99e74aed-7827-481a-9f22-8a47fdb9fb78.png)

![xpGUi9M](https://user-images.githubusercontent.com/109803937/224331333-9178e57f-1bcd-492e-a7b0-2b8a983d64df.png)

**Comment by thewhiteninja** [comment]
I can reproduce it. Thanks for providing the code 👍 

You can't open any volume with the NTFSExplorer, only NTFS.
You can add: `if (!commands::helpers::is_ntfs(disk, volume)) continue;` before creation of the NTFSExplorer.
Actually, I use that at the beginning of each command that requires a NTFS volume https://github.com/thewhiteninja/ntfstool/blob/01e7ef9b0933453d2c5b4d6f78be14700e9a8139/Sources/Commands/command_mft.dump.cpp#L26

Seems to work with after this change

**Comment by bleriaf** [comment]
oops, completely forgot about that. thanks so much!
