### ISSUE TITLE
ntfstool license expired

### ISSUE THREAD

**Issue by rocket748** [thewhiteninja/ntfstool#29]
ntfstool license expired???
![截屏2024-03-12 11 07 18](https://github.com/thewhiteninja/ntfstool/assets/67859916/5d2853b8-8096-43da-b991-5c6d556aa407)

**Comment by rocket748** [comment]
![image](https://github.com/thewhiteninja/ntfstool/assets/67859916/c0bbce47-51b9-47ea-bafe-466799644fad)
我请问呢

**Comment by thewhiteninja** [comment]
wrong repo, it's not my ntfstool :)

**Comment by rocket748** [comment]
ao sry
