### ISSUE TITLE
Is it possible to dump a $MFT file from a forensic image (E01)?

### ISSUE THREAD

**Issue by leoplac** [thewhiteninja/ntfstool#30]
Hi, I didnt find anywhere but I would like to dump the information and use the other functions in a $MFT file exported from a forensic image (E01).

Is there anyway to do that? IS that a feature?

**Comment by thewhiteninja** [comment]
Yes but you need to mount the e01 image first using tools like [OSF Mount](https://www.osforensics.com/tools/mount-disk-images.html) or [others](https://www.hackingarticles.in/multiple-ways-to-mount-raw-images-windows/)

Then you should be able to see the new drive / volume and dump the $MFT.
