### ISSUE TITLE
Support mounted volumes - for example created with VeraCrypt.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [thewhiteninja/ntfstool#6]
Hi,

Great tool :) Can you please modify volume selection process to allow user to select volumes created by VeraCrypt for example? VeraCrypt uses on the fly encryption so recovery process should work as on physical drive, right ? We just need a way to select them.

Thanks and have a nice day.

**Comment by thewhiteninja** [comment]
With the last commit (bba038e8190b6a8a81948e3708ff5bd2f03bdf05), you should be able to list virtual volumes.

Tested with VeraCrypt only but it should also work with TrueCrypt.
